# Generated by Django 5.1.7 on 2025-03-10 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Date_Naissance', models.DateField()),
                ('Adresse', models.TextField()),
                ('Poste', models.CharField(max_length=30)),
                ('Employe_non_Conforme', models.CharField(max_length=5)),
                ('Employe_Suspendu', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('Version', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Point_Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Adresse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adresse', models.TextField()),
                ('Temp_position', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Avertissement_retard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avertissement', models.TextField()),
                ('Id_Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Information', models.TextField()),
                ('Id_formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formulaire')),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Etat', models.CharField(max_length=20)),
                ('Temp_arv_est_pos', models.TimeField()),
                ('Temp_arv_reel_pos', models.TimeField()),
                ('Problem', models.TextField()),
                ('Id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employe')),
                ('Id_formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formulaire')),
                ('Id_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.point_vente')),
            ],
        ),
        migrations.CreateModel(
            name='Repense_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reponse', models.TextField()),
                ('Id_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('Id_visite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.visite')),
            ],
        ),
    ]
