# Generated by Django 5.1.7 on 2025-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='Employe_Suspendu',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Employe_non_Conforme',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Poste',
            field=models.CharField(choices=[('Responsable Generale', 'Responsable Generale'), ('Responsable Marchandiseur', 'Responsable Marchandiseur'), ('Responsable Superviseur', 'Responsable Superviseur'), ('Marchandiseur', 'Marchandiseur'), ('Superviseur', 'Superviseur')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='Version',
            field=models.FloatField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
