# Generated by Django 5.1.7 on 2025-03-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employe_employe_suspendu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='Temp_position',
            new_name='Heure_de_capture',
        ),
        migrations.AlterField(
            model_name='visite',
            name='Etat',
            field=models.CharField(choices=[('Prevu', 'Prevu'), ('En cours', 'En cours'), ('Reussie', 'Reussie')], max_length=20),
        ),
    ]
