# Generated by Django 5.1.7 on 2025-03-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_temp_position_position_heure_de_capture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='Mote_passe',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='employe',
            name='Nom_utilisateur',
            field=models.CharField(default='null', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='visite',
            name='Arrive',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=5),
        ),
    ]
