# Generated by Django 5.1.7 on 2025-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employe_mote_passe_employe_nom_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='Mote_passe',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Nom_utilisateur',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='Arrive',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='Problem',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='Temp_arv_est_pos',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='Temp_arv_reel_pos',
            field=models.TimeField(null=True),
        ),
    ]
