# Generated by Django 5.1.7 on 2025-04-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employe_mote_passe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='Version',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
