# Generated by Django 5.1.7 on 2025-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_formulaire_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='Version',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
