# Generated by Django 5.1.7 on 2025-04-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_formulaire_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point_vente',
            name='Adresse',
        ),
    ]
