# Generated by Django 5.1.7 on 2025-04-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_point_vente_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_vente',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='point_vente',
            name='Longtitude',
            field=models.FloatField(null=True),
        ),
    ]
