# Generated by Django 5.1.7 on 2025-04-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_point_vente_latitude_point_vente_longtitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_vente',
            name='Adresse',
            field=models.TextField(null=True),
        ),
    ]
