# Generated by Django 5.1.7 on 2025-05-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_point_vente_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='Id_visite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.visite'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='Etat',
            field=models.CharField(choices=[('Prevu', 'Prevu'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Non Effectue', 'Non Effectue')], max_length=20),
        ),
    ]
