# Generated by Django 5.1.7 on 2025-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_position_id_visite_alter_visite_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='Employe_Suspendu',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Employe_non_Conforme',
        ),
        migrations.AlterField(
            model_name='visite',
            name='Etat',
            field=models.CharField(choices=[('Prevu', 'Prevu'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Rapport en attente', 'Rapport en attente'), ('Non Effectue', 'Non Effectue')], max_length=20),
        ),
    ]
