# Generated by Django 5.1.7 on 2025-05-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_employe_employe_suspendu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='Information',
        ),
        migrations.AddField(
            model_name='case',
            name='Question',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='Type_reponse',
            field=models.TextField(choices=[('Number', 'Number'), ('Boolean', 'Boolean'), ('Text', 'Text')], null=True),
        ),
    ]
