# Generated by Django 5.1.7 on 2025-05-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_case_information_case_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visite',
            old_name='Problem',
            new_name='Infomationssupplementaires',
        ),
        migrations.AddField(
            model_name='visite',
            name='Problemes',
            field=models.TextField(null=True),
        ),
    ]
