# Generated by Django 5.1.7 on 2025-05-24 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_problem_visite_infomationssupplementaires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repensesformulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_file', models.URLField(null=True)),
                ('Id_visite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.visite')),
            ],
        ),
        migrations.DeleteModel(
            name='Repense_case',
        ),
    ]
