# Generated by Django 5.1.7 on 2025-05-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_repensesformulaire_delete_repense_case'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repensesformulaire',
            new_name='Rapportvisite',
        ),
        migrations.RemoveField(
            model_name='point_vente',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='point_vente',
            name='Longtitude',
        ),
        migrations.RemoveField(
            model_name='visite',
            name='Arrive',
        ),
        migrations.AddField(
            model_name='avertissement_retard',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='visite',
            name='Type',
            field=models.CharField(choices=[('Planifie', 'Planifie'), ('Libre', 'Libre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='Id_formulaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.formulaire'),
        ),
    ]
